[34m[1mwandb[0m: [33mWARNING[0m No relevant files were detected in the specified directory. No code will be logged to your run.
Traceback (most recent call last):
  File "/Users/dganjali/.pyenv/versions/3.10.13/lib/python3.10/site-packages/gymnasium/utils/save_video.py", line 13, in <module>
    from moviepy.video.io.ImageSequenceClip import ImageSequenceClip
ModuleNotFoundError: No module named 'moviepy'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/dganjali/Documents/GitHub/FinalCSP/reinforcement/tetris/train.py", line 251, in <module>
    envs = gym.vector.SyncVectorEnv(
  File "/Users/dganjali/.pyenv/versions/3.10.13/lib/python3.10/site-packages/gymnasium/vector/sync_vector_env.py", line 86, in __init__
    self.envs = [env_fn() for env_fn in env_fns]
  File "/Users/dganjali/.pyenv/versions/3.10.13/lib/python3.10/site-packages/gymnasium/vector/sync_vector_env.py", line 86, in <listcomp>
    self.envs = [env_fn() for env_fn in env_fns]
  File "/Users/dganjali/Documents/GitHub/FinalCSP/reinforcement/tetris/train.py", line 132, in thunk
    env = gym.wrappers.RecordVideo(env, f"videos/{run_name}")
  File "/Users/dganjali/.pyenv/versions/3.10.13/lib/python3.10/site-packages/gymnasium/wrappers/rendering.py", line 273, in __init__
    from gymnasium.utils.save_video import capped_cubic_video_schedule
  File "/Users/dganjali/.pyenv/versions/3.10.13/lib/python3.10/site-packages/gymnasium/utils/save_video.py", line 15, in <module>
    raise gym.error.DependencyNotInstalled(
gymnasium.error.DependencyNotInstalled: moviepy is not installed, run `pip install "gymnasium[other]"`
